# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runTestSuite:
        description: 'Trigger Newman tests manually'
        required: true
        default: 'true'
        
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run API Tests
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json
