name: Newman Tests
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runTestSuite:
        description: 'Trigger Newman tests manually'
        required: true
        default: 'true'

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      - name: Make Directory for results
        run: mkdir -p testResults
        
      - name: Run API Tests
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: testResults
